import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

interface SvgDir {
	dir: string;
	prefix?: string;
	postfix?: string;
}

interface SvgComponentsOptions {
	dirs: SvgDir[];
	dts?: string;
}

function scanSvgFiles(dir: string): string[] {
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith('.svg'))
		.map((f) => path.resolve(dir, f));
}

// «ko-fi» → «KoFi», «some_icon» → «SomeIcon»
function toPascalCase(str: string): string {
	return str
		.replace(/[-_](.)/g, (_, char) => char.toUpperCase())
		.replace(/^(.)/, (_, char) => char.toUpperCase());
}

function resolveDir(dir: string, root: string): string {
	if (dir.startsWith('@/')) {
		return path.resolve(root, 'src', dir.slice(2));
	}
	if (path.isAbsolute(dir)) return dir;
	return path.resolve(root, dir);
}

function toImportPath(absFilePath: string, root: string): string {
	const rel = path.relative(path.resolve(root, 'src'), absFilePath);
	return '@/' + rel.replace(/\\/g, '/');
}

interface SvgEntry {
	componentName: string;
	importPath: string;
	absPath: string;
}

function collectEntries(dirs: SvgDir[], root: string): SvgEntry[] {
	const entries: SvgEntry[] = [];

	for (const { dir, prefix = '', postfix = '' } of dirs) {
		const absDir = resolveDir(dir, root);

		if (!fs.existsSync(absDir)) {
			console.warn(`[vite-plugin-svg-components] Directory not found: ${absDir}`);
			continue;
		}

		const files = scanSvgFiles(absDir);

		for (const absPath of files) {
			const baseName = path.basename(absPath, '.svg');
			const pascal = toPascalCase(baseName);
			const componentName = `${prefix}${pascal}${postfix}`;
			const importPath = toImportPath(absPath, root);

			entries.push({ componentName, importPath, absPath });
		}
	}

	return entries.sort((a, b) => a.componentName.localeCompare(b.componentName));
}

function generateDts(entries: SvgEntry[]): string {
	const lines = entries.map(
		({ componentName, importPath }) =>
			`    ${componentName}: typeof import('${importPath}')['default']`
	);

	const globalLines = entries.map(
		({ componentName, importPath }) =>
			`  const ${componentName}: typeof import('${importPath}')['default']`
	);

	return `/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-svg-components

import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
${lines.join('\n')}
  }
}

// For TSX support
declare global {
${globalLines.join('\n')}
}
`;
}

export default function svgComponents(options: SvgComponentsOptions): Plugin {
	const { dirs, dts = 'src/svg-components.d.ts' } = options;
	let root: string;
	let entries: SvgEntry[] = [];

	function rebuild() {
		entries = collectEntries(dirs, root);

		if (dts) {
			const dtsPath = path.resolve(root, dts);
			fs.mkdirSync(path.dirname(dtsPath), { recursive: true });
			fs.writeFileSync(dtsPath, generateDts(entries), 'utf-8');
		}
	}

	return {
		name: 'vite-plugin-svg-components',
		enforce: 'pre',

		configResolved(config) {
			root = config.root;
			rebuild();
		},

		transform(code, id) {
			if (!id.endsWith('.vue') && !id.includes('.vue?')) return;

			let transformed = code;
			let changed = false;

			for (const { componentName, importPath } of entries) {
				const usedInTemplate = new RegExp(`<${componentName}[\\s/>]`).test(code);
				const usedInScript = new RegExp(`['"\`]${componentName}['"\`]|\\b${componentName}\\b`).test(
					code
				);

				if (usedInTemplate || usedInScript) {
					const scriptSetupMatch = transformed.match(/<script\s[^>]*setup[^>]*>/);
					if (scriptSetupMatch) {
						const insertAfter = scriptSetupMatch.index! + scriptSetupMatch[0].length;
						transformed =
							transformed.slice(0, insertAfter) +
							`\nimport ${componentName} from '${importPath}'` +
							transformed.slice(insertAfter);
						changed = true;
					}
				}
			}

			if (changed) return transformed;
		},

		configureServer(server) {
			const watchedDirs = dirs.map(({ dir }) => resolveDir(dir, root));

			server.watcher.add(watchedDirs);

			server.watcher.on('add', (file) => {
				if (file.endsWith('.svg') && watchedDirs.some((d) => file.startsWith(d))) {
					rebuild();
					server.moduleGraph.invalidateAll();
				}
			});

			server.watcher.on('unlink', (file) => {
				if (file.endsWith('.svg') && watchedDirs.some((d) => file.startsWith(d))) {
					rebuild();
					server.moduleGraph.invalidateAll();
				}
			});
		},
	};
}
