/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-svg-components

import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconBackgrounds: typeof import('@/assets/images/icons/backgrounds.svg')['default']
    LogoGithub: typeof import('@/assets/images/resources/github.svg')['default']
    LogoKoFi: typeof import('@/assets/images/resources/ko-fi.svg')['default']
    LogoPronounsPage: typeof import('@/assets/images/resources/pronouns-page.svg')['default']
    LogoSpotify: typeof import('@/assets/images/resources/spotify.svg')['default']
    LogoTelegram: typeof import('@/assets/images/resources/telegram.svg')['default']
    LogoTwitter: typeof import('@/assets/images/resources/twitter.svg')['default']
  }
}

// For TSX support
declare global {
  const IconBackgrounds: typeof import('@/assets/images/icons/backgrounds.svg')['default']
  const LogoGithub: typeof import('@/assets/images/resources/github.svg')['default']
  const LogoKoFi: typeof import('@/assets/images/resources/ko-fi.svg')['default']
  const LogoPronounsPage: typeof import('@/assets/images/resources/pronouns-page.svg')['default']
  const LogoSpotify: typeof import('@/assets/images/resources/spotify.svg')['default']
  const LogoTelegram: typeof import('@/assets/images/resources/telegram.svg')['default']
  const LogoTwitter: typeof import('@/assets/images/resources/twitter.svg')['default']
}
